"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['Advanced Course Cover.jpeg', 'Advanced Course Q1.png', 'Advanced Course Q2.png',
              'Advanced Course Q3.png', 'advanced_teacher.png', 'age_12.png', 'AtarianSystem.ttf',
              'Basic Course Cover.jpeg', 'Basic Course Q1.png', 'Basic Course Q2.png', 'Basic Course Q3.png',
              'basic_course_boring.wav', 'basic_course_teaching.wav', 'basic_teacher.png', 'basketball 2.png',
              'basketball_minigame_theme_track.wav', 'basketball_score.wav', 'beep.wav', 'binary-code.png',
              'boy.png', 'cipher.wav', 'coin.png', 'dot.png', 'heart.png', 'hills_of_radiant_winds.wav',
              'hoop.png', 'husband.png', 'injustice.wav', 'laugh.wav', 'math_minigame_theme_track.wav', 'NineTsuki.otf',
              'pfft.wav', 'player_front.png', 'player_front_face.png', 'player_left.png', 'player_right.png',
              'so_random.wav', 'student_complaint.wav', 'trash_talk.wav', 'tryouts_apology.wav', 'Turok.otf',
              'whistle.wav', 'wire_connect.wav', 'wire_minigame_theme_track.wav', 'worker.png',
              'worker_conversation.wav']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)